// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Suite Test Math learning', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test-open', async function() {
    await driver.get("http://localhost:3000//")
    await driver.manage().window().setRect(746, 824)
    await driver.findElement(By.css(".btn")).click()
  })
  it('test-login-fail', async function() {
    await driver.get("http://localhost:3000//login")
    await driver.findElement(By.name("email")).sendKeys("nguyentiep132@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("1312311")
    await driver.findElement(By.id("loginbutton")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "Account Invalid")
  })
  it('test-login-true', async function() {
    await driver.get("http://localhost:3000//login")
    await driver.findElement(By.name("email")).sendKeys("nguyentiep@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.id("loginbutton")).click()
    await driver.findElement(By.css(".btn")).click()
  })
  it('test-create-success', async function() {
    await driver.get("http://localhost:3000//login")
    await driver.findElement(By.id("create")).click()
    await driver.findElement(By.name("name")).sendKeys("NguyenTiep")
    await driver.findElement(By.name("email")).sendKeys("tiepuet2006@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("nguyentiep")
    {
      const dropdown = await driver.findElement(By.id("sel1"))
      await dropdown.findElement(By.xpath("//option[. = 'Teacher']")).click()
    }
    await driver.findElement(By.id("create")).click()
    await driver.close()
  })
  it('test-game-1', async function() {
    await driver.get("http://localhost:3000//")
    await driver.manage().window().setRect(1920, 1080)
    await driver.findElement(By.id("loginbutton")).click()
    await driver.findElement(By.css(".item-lesson:nth-child(1) .rounded")).click()
    {
      const dragged = await driver.findElement(By.id("4"))
      const dropped = await driver.findElement(By.id("9"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("1"))
      const dropped = await driver.findElement(By.id("6"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("7"))
      const dropped = await driver.findElement(By.id("5"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("1"))
      const dropped = await driver.findElement(By.id("10"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("8"))
      const dropped = await driver.findElement(By.id("3"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("2"))
      const dropped = await driver.findElement(By.id("6"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
  })
  it('test-game-2', async function() {
    await driver.get("http://localhost:3000//")
    await driver.findElement(By.css(".item-lesson:nth-child(2) .rounded")).click()
    {
      const dragged = await driver.findElement(By.id("3"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("2"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("4"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("6"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("2"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("1"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("7"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("4"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("6"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("1"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("3"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("4"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("6"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("1"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    {
      const dragged = await driver.findElement(By.id("2"))
      const dropped = await driver.findElement(By.id("drop-frame"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    await driver.findElement(By.css(".buy")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    assert(await driver.getTitle() == "Win")
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.close()
  })
})
